#!/usr/bin/env sh

# original from https://github.com/lmaotrigine/heartbeat-unix/blob/master/scripts/heartbeat-client-macOS.sh
# has been adapted

HEARTBEAT_HOME=${HEARTBEAT_HOME:-$HOME/.heartbeat}
HEARTBEAT_LOG_DIR=$HEARTBEAT_HOME/logs

# shellcheck source=/dev/null
[ -f "$HEARTBEAT_HOME/config" ] && . "$HEARTBEAT_HOME/config"

# https://stackoverflow.com/questions/11505255/osx-check-if-the-screen-is-locked
function screenIsUnlocked {
    [ "$(/usr/libexec/PlistBuddy -c "print :IOConsoleUsers:0:CGSSessionScreenIsLocked" /dev/stdin 2>/dev/null <<< "$(ioreg -n Root -d1 -a)")" != "true" ] && return 0 || return 1;
}

if [ -z "$HEARTBEAT_AUTH" ] || [ -z "$HEARTBEAT_HOSTNAME" ]; then
    echo "Environment variables not setup correctly!"
    echo "HEARTBEAT_AUTH: $HEARTBEAT_AUTH"
    echo "HEARTBEAT_LOG_DIR: $HEARTBEAT_LOG_DIR"
    echo "HEARTBEAT_HOSTNAME: $HEARTBEAT_HOSTNAME"
    exit 1
else
    # Make log dir if it doesn't exist
    if ! [ -d "$HEARTBEAT_LOG_DIR" ]; then
        mkdir -p "$HEARTBEAT_LOG_DIR" || exit 1
    fi

    # Check when the last HID event was sent
    LAST_INPUT_SEC="$(($(ioreg -c IOHIDSystem | sed -e '/HIDIdleTime/ !{ d' -e 't' -e '}' -e 's/.* = //g' -e 'q') / 1000000000))"

    if [ $LAST_INPUT_SEC -lt 120 ]; then
        # launchd seems to run even when the lid is shut, so we check if the screen is unlocked
        if screenIsUnlocked; then
            {
                echo "$(date +"%Y/%m/%d %T") - Running Heartbeat"
                curl -s -X POST -H "Authorization: $HEARTBEAT_AUTH" "$HEARTBEAT_HOSTNAME/api/beat"
                echo ""
            } >> "$HEARTBEAT_LOG_DIR/heartbeat.log" 2>&1
        fi
    fi
fi
